CREATE TABLE TMARCAJE (
  COD_MARCAJE bigint AUTO_INCREMENT PRIMARY KEY,
  COD_TIPO_MARCAJE integer,
  COD_EMPLEADO integer,
  COD_BIO integer,
  FEC_MARCAJE datetime,
  HOR_MARCAJE datetime,
  FEC_GRABACION datetime,
  HOR_GRABACION datetime,
  IND_INCIDENCIA char(1) NULL,
  IND_PENDIENTE char(1) NULL,
  DES_OBSERVACIONES varchar(100) NULL
)
GO

CREATE TABLE TEMPLEADO (
  COD_EMPLEADO integer AUTO_INCREMENT PRIMARY KEY,
  COD_USUARIO INTEGER NULL,
  NOM_EMPLEADO varchar(20),
  APE1_EMPLEADO varchar(20),
  APE2_EMPLEADO varchar(20),
  CONTACTO_EMPLEADO varchar(20) NULL,
  FEC_ALTA datetime,
  NOM_USUARIO_ALTA varchar(20),
  FEC_BAJA DATETIME NULL,
  NOM_USUARIO_BAJA varchar(20) NULL
)
GO

CREATE TABLE TBIO (
  COD_BIO integer AUTO_INCREMENT PRIMARY KEY,
  COD_TIPO_BIO integer,
  DATO_BIO variant,
  COD_EMPLEADO integer,
  FEC_ALTA datetime,
  NOM_USUARIO_ALTA varchar(20),
  FEC_BAJA DATETIME NULL,
  NOM_USUARIO_BAJA varchar(20) NULL
)
GO

CREATE TABLE TTBIO (
  COD_TIPO_BIO integer AUTO_INCREMENT PRIMARY KEY,
  DES_BIO varchar(20),
  FEC_ALTA datetime,
  NOM_USUARIO_ALTA varchar(20),
  FEC_BAJA DATETIME NULL,
  NOM_USUARIO_BAJA varchar(20) NULL
)
GO

CREATE TABLE TUSUARIO (
  COD_USUARIO integer AUTO_INCREMENT PRIMARY KEY,
  NOM_LOGIN varchar(20),
  FEC_ALTA datetime,
  NOM_USUARIO_ALTA varchar(20),
  FEC_BAJA DATETIME NULL,
  NOM_USUARIO_BAJA varchar(20) NULL
)
GO

CREATE TABLE TROL (
  COD_ROL integer AUTO_INCREMENT PRIMARY KEY,
  NOM_ROL varchar(20),
  FEC_ALTA datetime,
  NOM_USUARIO_ALTA varchar(20),
  FEC_BAJA DATETIME NULL,
  NOM_USUARIO_BAJA varchar(20) NULL
)
GO

CREATE TABLE TUSUARIOROL (
  COD_USUARIO integer,
  COD_ROL integer
)
GO

CREATE TABLE TTRANSACCIONES (
  COD_TRANSACCION bigint AUTO_INCREMENT PRIMARY KEY,
  TIP_TRANS varchar(5),
  DESC_TRANS varchar(30) NULL,
  COD_OBJ integer,
  NOM_OBJ varchar(20) NULL,
  COD_USUARIO integer,
  FEC_SIS datetime,
  HOR_SIS datetime,
  IP_USUARIO varchar(15)
)
GO

ALTER TABLE [TMARCAJE] ADD FOREIGN KEY ([COD_EMPLEADO]) REFERENCES [TEMPLEADO] ([COD_EMPLEADO])
GO

ALTER TABLE [TUSUARIO] ADD FOREIGN KEY ([COD_USUARIO]) REFERENCES [TEMPLEADO] ([COD_USUARIO])
GO

ALTER TABLE [TMARCAJE] ADD FOREIGN KEY ([COD_BIO]) REFERENCES [TBIO] ([COD_BIO])
GO

ALTER TABLE [TUSUARIOROL] ADD FOREIGN KEY ([COD_USUARIO]) REFERENCES [TUSUARIO] ([COD_USUARIO])
GO

ALTER TABLE [TUSUARIOROL] ADD FOREIGN KEY ([COD_ROL]) REFERENCES [TROL] ([COD_ROL])
GO

ALTER TABLE [TBIO] ADD FOREIGN KEY ([COD_EMPLEADO]) REFERENCES [TEMPLEADO] ([COD_EMPLEADO])
GO

ALTER TABLE [TBIO] ADD FOREIGN KEY ([COD_TIPO_BIO]) REFERENCES [TTBIO] ([COD_TIPO_BIO])
GO

ALTER TABLE [TTRANSACCIONES] ADD FOREIGN KEY ([COD_USUARIO]) REFERENCES [TUSUARIO] ([COD_USUARIO])
GO
